ci tests fixes

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,7 +10,7 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK
-      uses: actions/setup-java@v3.4.0
+      uses: actions/setup-java@v1
       with:
         java-version: '11'
     - name: Setup Android SDK
@@ -19,11 +19,14 @@ jobs:
       run: chmod +x ./gradlew
     - name: Run Tests                  
       run: ./gradlew test
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: always()
+    - uses: actions/upload-artifact@v2  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
       with:
-        name: Test Results        
-        path: test-reports/TEST-*.xml    # Path to test results
-        reporter: java-junit        # Format of test results
-        fail-on-error: true  
+        name: test-results
+        path: java-junit.xml
+    - uses: dorny/test-reporter@v1
+      with:
+        artifact: test-results            # artifact name
+        name: java Tests                  # Name of the check run which will be created
+        path: '*.xml'                     # Path to test results (inside artifact .zip)
+        reporter: java-junit             # Format of test results    
